# Generated by Django 3.0.7 on 2020-07-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='My Description'),
            preserve_default=False,
        ),
    ]
